name: Build Allfight Minecraft 1.5.1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 6
      uses: actions/setup-java@v2
      with:
        java-version: '1.6'
        distribution: 'adoptopenjdk'  # Spécifiez la distribution ici
        architecture: 'x64'

    - name: Install dependencies (if needed)
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    - name: Compile with Maven
      run: mvn clean package

    - name: Upload the built jar as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allfight.jar
        path: target/allfight.jar

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: target/allfight.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
