name: Build Allfight Minecraft 1.5.1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 6
      uses: actions/setup-java@v2
      with:
        java-version: '1.6'
        architecture: 'x64'

    - name: Install dependencies (if needed)
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    - name: Compile with Maven
      run: mvn clean package

    - name: Upload the built jar as artifact
      uses: actions/upload-artifact@v2
      with:
        name: allfight.jar
        path: target/allfight.jar

    - name: Create GitHub Release
      id: create_release
      uses: gh-actions/create-release@v1
      with:
        tag_name: v1.0.0 # Vous pouvez changer cette version selon vos besoins
        release_name: "Release Allfight Minecraft 1.5.1"
        body: "Version compilée de Allfight.jar"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Jar to Release
      uses: gh-actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/allfight.jar
        asset_name: allfight.jar
        asset_content_type: application/java-archive
