name: Build Allfight Minecraft 1.5.1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ajout des permissions nécessaires
      actions: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install OpenJDK 6
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget "https://cdn.discordapp.com/attachments/1173100774126010370/1314048665761091595/jdk-6u45-linux-x64.bin?ex=67525aaf&is=6751092f&hm=ade3cd70137c46484cfee4e47d7da999f6841f513aabbfec101e8bfde732f954&" -O jdk-6u45-linux-x64.bin
        chmod +x jdk-6u45-linux-x64.bin
        sudo mkdir -p /usr/local/java
        sudo ./jdk-6u45-linux-x64.bin
        sudo mv jdk1.6.0_45 /usr/local/java/
        echo "export JAVA_HOME=/usr/local/java/jdk1.6.0_45" >> ~/.bashrc
        echo "export PATH=$JAVA_HOME/bin:$PATH" >> ~/.bashrc
        source ~/.bashrc

    - name: Install dependencies (if needed)
      run: |
        sudo apt-get install -y maven

    - name: Compile with Maven
      run: mvn clean package

    - name: Check if JAR exists
      run: |
        if [ ! -f target/allfight-1.5.1-SNAPSHOT.jar ]; then
          echo "JAR file not found! Aborting the workflow."
          exit 1
        fi

    - name: Upload the built jar as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allfight.jar
        path: target/allfight-1.5.1-SNAPSHOT.jar

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: target/allfight-1.5.1-SNAPSHOT.jar
        tag_name: v1.0.0 # Specify a tag for the release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
