name: Build Allfight Minecraft 1.5.1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install OpenJDK 6
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://archive.apache.org/dist/openjdk/jdk6/6u45-b06/jdk-6u45-linux-x64.bin
        chmod +x jdk-6u45-linux-x64.bin
        sudo mkdir -p /usr/local/java
        sudo ./jdk-6u45-linux-x64.bin
        sudo mv jdk1.6.0_45 /usr/local/java/
        echo "export JAVA_HOME=/usr/local/java/jdk1.6.0_45" >> ~/.bashrc
        echo "export PATH=$JAVA_HOME/bin:$PATH" >> ~/.bashrc
        source ~/.bashrc

    - name: Install dependencies (if needed)
      run: |
        sudo apt-get install -y maven

    - name: Compile with Maven
      run: mvn clean package

    - name: Upload the built jar as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allfight.jar
        path: target/allfight.jar

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: target/allfight.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
