name: Build Allfight Minecraft 1.5.1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install OpenJDK 6 from local file
      run: |
        # Déplacer le fichier JDK téléchargé dans le répertoire approprié
        sudo mkdir -p /usr/local/java
        sudo mv jdk-6u45-linux-x64.bin /usr/local/java/
        
        # Donner les permissions d'exécution au fichier
        sudo chmod +x /usr/local/java/jdk-6u45-linux-x64.bin
        
        # Extraire le contenu du fichier binaire
        sudo /usr/local/java/jdk-6u45-linux-x64.bin
        
        # Déplacer le dossier d'installation de JDK vers un répertoire standard
        sudo mv /usr/local/java/jdk1.6.0_45 /usr/local/java/
        
        # Ajouter les variables d'environnement pour JAVA_HOME et PATH
        echo "export JAVA_HOME=/usr/local/java/jdk1.6.0_45" >> ~/.bashrc
        echo "export PATH=$JAVA_HOME/bin:$PATH" >> ~/.bashrc
        source ~/.bashrc

    - name: Install dependencies (if needed)
      run: |
        sudo apt-get install -y maven

    - name: Compile with Maven
      run: mvn clean package

    - name: Upload the built jar as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allfight.jar
        path: target/allfight.jar

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: target/allfight.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
